### ISSUE TITLE
shonenjump_chpwd:4: formato de ejecutable incorrecto: shonenjump 

### ISSUE THREAD

**Issue by cocodrino** [suzaku/shonenjump#1]
Hi, sorry but I've installed shonenjump and now after every command (cd cd .. ls etc) I get this error

shonenjump_chpwd:4: formato de ejecutable incorrecto: shonenjump 

the translation would be something like wrong executable format

do you know how solve this error? thanks

**Comment by suzaku** [comment]
@cocodrino Hi, thanks for reporting the error. Could you please tell me which OS and shell you are using?

**Comment by cocodrino** [comment]
hi...I'm using arch linux and zshrc

**Comment by suzaku** [comment]
@cocodrino It seemed like you were using an OS and architecture combination that I didn't pre-built a binary for.

You can try building the executable yourself if you have `Go` installed on your machine, it's very easy.

**Comment by suzaku** [comment]
Just run `go build github.com/suzaku/shonenjump` if you have `Go` installed.
