### ISSUE TITLE
Creating a new release?

### ISSUE THREAD

**Issue by patrickdavey** [suzaku/shonenjump#2]
Hi there,

I was just looking for a way to use autojump without having to have python - and your go version looks great.

I just note that it says on the downloads page that "there have been 9 commits to master" since those versions were compiled.

Is it worth me compiling myself or are those downloaded versions still good?

**Comment by suzaku** [comment]
@patrickdavey Thanks for being interested. The latest released version is v0.6, later commits are mostly refactoring, so you can just download the v0.6 version built for your platform.
