### ISSUE TITLE
AUR build ?

### ISSUE THREAD

**Issue by hiimdoublej** [suzaku/shonenjump#5]
As title, an AUR build would make it easier to install for Arch Linux users.

**Comment by suzaku** [comment]
Thanks for your suggestion. But I don't use Arch Linux in a daily base, could you share a tutorial with me on how to create a AUR build and how to test it?

**Comment by suzaku** [comment]
Would a Snapcraft build make your life easier? If it is, I can set up one.

**Comment by graysky2** [comment]
@suzaku @hiimdoublej - I took a stab at one: https://aur.archlinux.org/packages/shonenjump/

I am not very experienced with `go` for builds so I do not know if my invocation is correct.  Further, `namcap` is complaining about my LDFLAGS:

```
% namcap shonenjump-0.7.20-1-x86_64.pkg.tar.zst 
shonenjump W: ELF file ('usr/bin/shonenjump') lacks FULL RELRO, check LDFLAGS.
```

Thoughts?

**Comment by suzaku** [comment]
@graysky2 Thanks very much. 

I'm not familiar with AUR, where can I see your configuration? I can try my best to figure out what might be wrong there.

**Comment by graysky2** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=shonenjump

**Comment by suzaku** [comment]
Do we have to use `-v -buildmode=pie -ldflags "-extldflags \"$LDFLAGS\""` when building a Go binary for AUR?
I only use `go build .` when building in my development environment.

**Comment by graysky2** [comment]
@suzaku - I get warnings from the distro package audit util if I do not:
```
% namcap shonenjump-0.7.20-2-x86_64.pkg.tar.zst
shonenjump W: ELF file ('usr/bin/shonenjump') lacks FULL RELRO, check LDFLAGS.
shonenjump W: ELF file ('usr/bin/shonenjump') lacks PIE.
```

**Comment by suzaku** [comment]
Can you try something like `go build -v -ldflags "-buildmode=pie"`? 
I see a similar configuration [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kafkactl)

**Comment by graysky2** [comment]
That syntax seems fine for the PIE warning but it does not fix up the FULL RELRO one.
```
  export CGO_LDFLAGS="$LDFLAGS"
  go build -v -ldflags "-buildmode=pie"
```

**Comment by suzaku** [comment]
How about this `go build -buildmode=pie -ldflags '-linkmode=external -extldflags=-Wl,-z,relro,-z,now'`? ([ref](https://github.com/golang/go/issues/44480))

**Comment by graysky2** [comment]
That did it, thanks.

```
go build -buildmode=pie -ldflags "-linkmode=external -extldflags=$LDFLAGS"
```

No warnings from `namcap` on the resulting package.

You might wanna edit your README to point Arch Linux users to the AUR package.

**Comment by suzaku** [comment]
Does the `j` command work now in your environment? You can try `cd` around and then run `j -stat` and `j -purge`.

**Comment by graysky2** [comment]
Yes, it works.  Tested under zsh and bash.

**Comment by suzaku** [comment]
Cool, thanks very much!

I'm not familiar with AUR, could you please add a `AUR` subsection under the `Linux` section?

**Comment by graysky2** [comment]
https://github.com/suzaku/shonenjump/pull/6

**Comment by suzaku** [comment]
Thanks. I can close this issue now. @hiimdoublej

**Comment by graysky2** [comment]
> https://github.com/suzaku/shonenjump/pull/6

The AUR (Arch User Repository) is just a place where Arch Linux users can submit an Arch-specific `PKGBUILD` for software.  It's like a gentoo ebuild.

**Comment by suzaku** [comment]
I see. Is there a command like `apt install` for `AUR`?

**Comment by graysky2** [comment]
No, the AUR does not store binary packages.  It stores the recipe for users to build them.  That is the `PKGBUILD` which keeps track of dependencies, and along with the Arch-specific build tool `makepkg` builds the binary package.

**Comment by suzaku** [comment]
Good to learn that, thanks.

**Comment by graysky2** [comment]
The advantage of using the PKGBUILD method is that it produces a package for use with the distro package manager, `pacman` so that all files are tracked and easily updated/removed.  A bit more sophisticated vs downloading and placing files manually :wink:

**Comment by suzaku** [comment]
How can I post new versions of this package on AUR? Ideally, I should integrate it into the build pipeline.

**Comment by graysky2** [comment]
You can take over the PKGBUILD if you want to maintain it.  It's just git.  Not sure how to do any integration though.

**Comment by suzaku** [comment]
I use `goreleaser` to push updates to my `Homebrew` tap, but `AUR` is not supported, so I guess I have to do the same manually.

**Comment by graysky2** [comment]
It's up to you.  Alternatively, I can continue to maintain it.  When you push a new release, just flag it out-of-date.  If you want to maintain it, let me know when you have an AUR account and I will disown the package; you can then adopt it and it's all yours.

**Comment by suzaku** [comment]
OK, thank you. Please continue to maintain it now, I guess I'll play with Arch Linux a little bit when I get a new non-Mac laptop.

**Comment by graysky2** [comment]
OK, let me know.  If you're using debian/ubuntu, transitioning to Arch is pretty straight forward.  I made the switch years ago and haven't looked back.  The Arch Way is very appealing to me and the package manager (`pacman`) and the build tools are very simple and elegant compared to how other distros do it.

If you want to read up a bit, the Arch wiki is a spectacular resource and the forums are very helpful/really friendly user base.

**Comment by suzaku** [comment]
I'm using macOS now. I have tried Manjaro for a short time before and it looked great.

**Comment by graysky2** [comment]
Be aware that Manjaro is not Arch.  It is _based_ on Arch but a different distro.

**Comment by suzaku** [comment]
I see. For me, it's like a newbie-friendly Arch.

**Comment by graysky2** [comment]
That's fine.  I believe Arch is more flexible but if you want something more friendly, that is your decision.
