### ISSUE TITLE
Correct way to build

### ISSUE THREAD

**Issue by graysky2** [suzaku/shonenjump#9]
I am maintaining the Arch Linux [PKGBUILD](https://aur.archlinux.org/packages/shonenjump) for shonenjump.  Is this the recommended way to build from source?

```
CGO_CPPFLAGS="${CPPFLAGS}" CGO_CFLAGS="${CFLAGS}" CGO_CXXFLAGS="${CXXFLAGS}" CGO_LDFLAGS="${LDFLAGS}" \
go build -buildmode=pie -ldflags "-linkmode external -extldflags \"${LDFLAGS}\""
```

**Comment by suzaku** [comment]
If you are in Linux, `go build .` should be enough to generate the `shonenjump` binary.

**Comment by suzaku** [comment]
BTW, I've updated `go.mod` to use go 1.19, so you might need to use a matching version of Go.

**Comment by graysky2** [comment]
Thanks
